---
extends: default

rules:
  line-length:
    max: 140
  # Allow standard GHA syntax for "on: *"
  truthy:
    ignore: '.github/workflows/*.yml'

ignore: |
  /submariner-k8s-broker/crds
  /submariner-operator/crds
  /submariner-k8s-broker/templates
  /submariner-operator/templates
