---
name: End to End Full

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

permissions: {}

jobs:
  e2e:
    name: E2E
    if: contains(github.event.pull_request.labels.*.name, 'ready-to-test')
    timeout-minutes: 45
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cable_driver: ['libreswan', 'wireguard', 'vxlan']
        globalnet: ['', 'globalnet']
        # Run most tests against the latest K8s version
        k8s_version: ['1.29']
        lighthouse: ['', 'lighthouse']
        include:
          # Bottom of supported K8s version range
          - k8s_version: '1.26'
    steps:
      - name: Check out the repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b

      - name: Run E2E deployment and tests
        uses: submariner-io/shipyard/gh-actions/e2e@devel
        with:
          k8s_version: ${{ matrix.k8s_version }}
          using: ${{ matrix.cable_driver }} ${{ matrix.globalnet }} ${{ matrix.lighthouse }}

      - name: Post mortem
        if: failure()
        uses: submariner-io/shipyard/gh-actions/post-mortem@devel
